name: generate animation

on:
  schedule: # execute automatically  every 12 hours
    - cron: "* */12 * * *"
    
  workflow_dispatch: # allows to manually run the job at any time
  
    # run on every push on the master branch
  push:
    branches:
    - master

jobs:
  generate:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    
    steps:
      # Snake Animation
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        id: snake-svg
        with:
          github_user_name: andersonrafhael
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
